services:

  app:
    build: .
    container_name: tripplanner-app

    ports:
      - "80:80"

    volumes:
      - .:/var/www/html

    depends_on:
      - db

  db:
    image: mariadb:10.11

    container_name: tripplanner-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this to your own MariaDB root password
      MYSQL_DATABASE: RoadTrip # Change this to your own MariaDB database name


    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
